import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/Navbar";
import Button from "./components/Button";
import ImageRadius from "./components/ImageRadius";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navbar />
        </div>
        <div className="separator">
           <h1>Hi
            <br/>I'm <span>Maxime</span>
            <br /> Web developer</h1>

        <ImageRadius 
           src="https://placehold.jp/250*250.png"
           alt="image home"
           width={350}
           height={350}
           />
        </div>
        <Button />
          
      </main>
    </>
  );
}
